entero c
inicio
 escriba "ingrese su edad"
 llamar nueva_linea
 lea c
 si(c>90)entonces 
   escriba "anciano"
   sino
     si(c>65) y (c<=90)entonces
     escriba "eres considerado de la tercera edad"
     sino
       si(c<=65)y(c>40)entonces
       escriba "eres considerado un adulto mayor"
       sino
        si(c<=40)y(c>17)entonces
        escriba "adulto"
        sino
          si(c<=17)y(c>15)entonces
          escriba "joven #cool"
          sino
           si(c<=15)y(c>10)entonces
           escriba "adolecente"
           sino
             si(c<=10)y(c>1)entonces
             escriba "niño"
             sino
               si(c<=1)entonces
               escriba "bebe"
               sino 
                escriba "no has nacido"
               fin si 
             fin si 
           fin si 
        
        fin si
       fin si     
     fin si
fin si  
fin si
fin
