entero i,j, suma, k,p
inicio
para i <-1 hasta 3 haga
llamar nueva_linea
llamar nueva_linea
escriba "Descanso"
llamar nueva_linea
para j <- 1 hasta 4 haga
 llamar nueva_linea
 escriba "j",j
 escriba "  i#",i
 llamar nueva_linea
 llamar nueva_linea
 para k <- 1 hasta 3 haga
 	  suma <- k + 1
 	  escriba suma
      llamar nueva_linea
 	  escriba "kk"
 fin para
fin para
fin para
fin