entero numero, suma
inicio
escriba "ACOMULADOR/SUMA"
llamar nueva_linea
llamar nueva_linea
  numero<-2
  suma<-0
  mientras (numero<=20) haga
    escriba " el numero es: "
    escriba numero
    llamar nueva_linea
    llamar nueva_linea 
    suma<-suma+numero
    numero<-numero+2
    llamar obtener_caracter
    escriba "la suma va en: " , suma
    llamar nueva_linea
  fin mientras
  escriba "la sumatoria total es: " , suma
fin    